@echo off
REM =====================================================================
REM  vps-nginx-fix.cmd  —  Wire report.heliontracking.com → Node:3002
REM  inside the CMSV nginx that actually owns port 443.
REM
REM  Run AFTER vps-nginx-debug.cmd confirms:
REM    - CMSV nginx PID owns :443
REM    - SSL cert files exist
REM    - /__whoami returns CMSV (not fleet) response
REM
REM  What this does:
REM    1. Writes helion-report-fleet.conf into CMSV nginx\conf\
REM    2. Injects  include helion-report-fleet.conf;  into nginx.conf
REM       (only if not already present)
REM    3. Tests config with the CMSV binary
REM    4. Reloads with the CMSV binary
REM    5. Smoke-tests /__whoami and /api/health
REM =====================================================================
setlocal enabledelayedexpansion

set CMSV_DIR=C:\Program Files\CMSServerV6\nginx
set CMSV_NGINX=%CMSV_DIR%\nginx.exe
set CMSV_CONF=%CMSV_DIR%\conf\nginx.conf
set FLEET_CONF=%CMSV_DIR%\conf\helion-report-fleet.conf
set SSL_CHAIN=C:\nginx\nginx-1.30.0\ssl\report.heliontracking.com-chain.pem
set SSL_KEY=C:\nginx\nginx-1.30.0\ssl\report.heliontracking.com-key.pem

echo.
echo === Pre-flight checks ===

if not exist "%CMSV_NGINX%" (
    echo [FAIL] CMSV nginx not found: %CMSV_NGINX%
    echo        Run vps-nginx-debug.cmd and find the real path.
    exit /b 1
)
echo [OK] CMSV nginx: %CMSV_NGINX%

if not exist "%SSL_CHAIN%" (
    echo [FAIL] SSL chain missing: %SSL_CHAIN%
    echo        Re-run win-acme for report.heliontracking.com first.
    exit /b 1
)
echo [OK] SSL chain: %SSL_CHAIN%

if not exist "%SSL_KEY%" (
    echo [FAIL] SSL key missing: %SSL_KEY%
    exit /b 1
)
echo [OK] SSL key: %SSL_KEY%

echo.
echo === Step 1: Write helion-report-fleet.conf ===

(
echo # Fleet Incident Reporter — report.heliontracking.com
echo # Generated by vps-nginx-fix.cmd
echo server {
echo     listen 443 ssl;
echo     server_name report.heliontracking.com;
echo.
echo     ssl_certificate     C:/nginx/nginx-1.30.0/ssl/report.heliontracking.com-chain.pem;
echo     ssl_certificate_key C:/nginx/nginx-1.30.0/ssl/report.heliontracking.com-key.pem;
echo.
echo     client_max_body_size 50m;
echo     proxy_read_timeout   600s;
echo     proxy_connect_timeout 60s;
echo     proxy_send_timeout   600s;
echo.
echo     add_header X-Report-Fleet yes always;
echo.
echo     location = /__whoami {
echo         return 200 "REPORT-SERVER-BLOCK\n";
echo     }
echo.
echo     location / {
echo         proxy_pass http://127.0.0.1:3002;
echo         proxy_http_version 1.1;
echo         proxy_set_header Upgrade $http_upgrade;
echo         proxy_set_header Connection "upgrade";
echo         proxy_set_header Host $host;
echo         proxy_set_header X-Real-IP $remote_addr;
echo         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
echo         proxy_set_header X-Forwarded-Proto $scheme;
echo     }
echo }
echo.
echo server {
echo     listen 80;
echo     server_name report.heliontracking.com;
echo     location /.well-known/acme-challenge/ {
echo         root C:/win-acme/webroot;
echo     }
echo     location / {
echo         return 301 https://$host$request_uri;
echo     }
echo }
) > "%FLEET_CONF%"
echo [OK] Wrote %FLEET_CONF%

echo.
echo === Step 2: Inject include into nginx.conf (if missing) ===

findstr /i "helion-report-fleet" "%CMSV_CONF%" >nul 2>&1
if %errorlevel% == 0 (
    echo [SKIP] include helion-report-fleet.conf already present in nginx.conf
) else (
    powershell -ExecutionPolicy Bypass -Command ^
        "$conf = Get-Content -LiteralPath '%CMSV_CONF%' -Encoding ascii;" ^
        "$out = New-Object System.Collections.Generic.List[string];" ^
        "$inserted = $false;" ^
        "foreach ($line in $conf) {" ^
            "$out.Add($line);" ^
            "if (-not $inserted -and $line -match 'mime\.types') {" ^
                "$out.Add('    include helion-report-fleet.conf;');" ^
                "$inserted = $true;" ^
            "}" ^
        "}" ^
        "if (-not $inserted) {" ^
            "Write-Error 'Could not find mime.types line — add include manually';" ^
            "exit 1;" ^
        "}" ^
        "$out | Set-Content -LiteralPath '%CMSV_CONF%' -Encoding ascii;" ^
        "Write-Host '[OK] Injected include helion-report-fleet.conf';"
    if errorlevel 1 (
        echo [FAIL] Could not patch nginx.conf automatically.
        echo        Manually add this line inside the http {} block:
        echo            include helion-report-fleet.conf;
        exit /b 1
    )
)

echo.
echo === Step 3: Test config ===
"%CMSV_NGINX%" -t
if errorlevel 1 (
    echo [FAIL] nginx config test failed — fix errors above before reloading.
    exit /b 1
)
echo [OK] Config test passed.

echo.
echo === Step 4: Reload nginx ===
"%CMSV_NGINX%" -s reload
if errorlevel 1 (
    echo [FAIL] nginx reload failed.
    exit /b 1
)
echo [OK] nginx reloaded.

echo.
echo === Step 5: Smoke test (wait 2s for reload) ===
timeout /t 2 /nobreak >nul

echo --- /__whoami (expect: REPORT-SERVER-BLOCK) ---
curl -sk https://127.0.0.1/__whoami -H "Host: report.heliontracking.com"
echo.

echo --- /api/health (expect: {"status":"ok",...}) ---
curl -sk https://127.0.0.1/api/health -H "Host: report.heliontracking.com"
echo.

echo --- X-Report-Fleet header present? ---
curl -skI https://127.0.0.1/ -H "Host: report.heliontracking.com" | findstr /i "X-Report-Fleet\|JSESSIONID"
echo.

echo.
echo === Done ===
echo If /__whoami returned REPORT-SERVER-BLOCK and /api/health returned JSON,
echo open https://report.heliontracking.com in your browser.
echo If you still see CMSV responses, run vps-nginx-debug.cmd and share output.
endlocal
